services:
  pvo-backend:
    build: ./pvo-backend
    command: npm run dev
    ports:
        - "3000:3000"
    volumes:
        - ./pvo-backend/:/pvo-backend/
        - /pvo-backend/node_modules
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vacations