services:
  pvo-backend:
    container_name: pvo-backend
    build: ./pvo-backend
    command: npm run dev
    ports:
        - "3000:3000"
    volumes:
        - ./pvo-backend/public/:/pvo-backend/public/
        - ./pvo-backend/src/:/pvo-backend/src/
        - /pvo-backend/node_modules
  pvo-frontend:
    container_name: pvo-frontend
    build: ./pvo-frontend
    command: npm run start
    ports:
        - "80:3000"
    volumes:
        - ./pvo-frontend/public/:/pvo-frontend/public/
        - ./pvo-frontend/src/:/pvo-frontend/src/
        - /pvo-frontend/node_modules
  db:
    container_name: pvo-db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vacations
